language: ruby
rvm:
  - 2.4.3

addons:
  postgresql: 9.6

before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"

script:
  - bin/rake db:create db:migrate RAILS_ENV=test
  - bin/rake
