meta_product_name: "Whikend | Trouvez votre partenaire de randonnée"
meta_description: "Whikend vous aide à trouver des partenaires de randonnée"
meta_image: "whikend-cover.jpg"                       # should exist in `app/assets/images/`
meta_title: "Whikend | Trouvez des partenaires de randonnée"
